# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: build
on:
  push:
    branches:
      - master

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.167.0"
      - name: Build
        run: |
          make build
